services:
    app:
        build: ./docker
        image: yurtkuran/damwidi
        ports:
            - '8080:80'
        volumes:
            # Mount source-code for development
            - ./:/var/www
        extra_hosts:
            - host.docker.internal:host-gateway
    db-mysql:
        image: mysql:5.7.40
        container_name: mySQL
        restart: always
        secrets:
            - db-password
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            # - MYSQL_DATABASE=damwidi
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.9.7
        container_name: pma
        links:
            - db-mysql
        environment:
            PMA_HOST: db-mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
            UPLOAD_LIMIT: 64M
        restart: always
        ports:
            - 8081:80
networks:
    public:
    private:
volumes:
    back-notused:
    db-data:
secrets:
    db-password:
        file: config/password.txt
